[package]
name = "bimber_ecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
any_vec = "0.11.0"
anymap = "0.12.1"
